
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 02 01:08:45 CST 2014
//----------------------------------------------------

package Compilers.Program;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int CFCLEAR = 1;
  public static final int PRED = 2;
  public static final int NOBBAG = 3;
  public static final int CLCLEAR = 4;
  public static final int FACINGW = 5;
  public static final int TURNLEFT = 6;
  public static final int FACINGS = 7;
  public static final int CRCLEAR = 8;
  public static final int RETURN = 9;
  public static final int NOT = 10;
  public static final int AND = 11;
  public static final int FACINGN = 12;
  public static final int OR = 13;
  public static final int PARAMCALL = 14;
  public static final int PARAM = 15;
  public static final int FACINGE = 16;
  public static final int CONDBRANCH = 17;
  public static final int ANYBBAG = 18;
  public static final int BRANCH = 19;
  public static final int DEFINST = 20;
  public static final int CFBLOCK = 21;
  public static final int NOFACINGW = 22;
  public static final int NONEXTB = 23;
  public static final int ITERATE = 24;
  public static final int SUCC = 25;
  public static final int MOVE = 26;
  public static final int NEXTB = 27;
  public static final int NOFACINGS = 28;
  public static final int CLBLOCK = 29;
  public static final int PICKBPR = 30;
  public static final int NOFACINGN = 31;
  public static final int CRBLOCK = 32;
  public static final int NOFACINGE = 33;
  public static final int IFZERO = 34;
  public static final int PUTBPR = 35;
  public static final int TURNOFF = 36; 
  public static final int CALL = 37;


}

