
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 03 19:29:45 UTC 2014
//----------------------------------------------------

package Compilers.Java;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int LKEY = 5;
  public static final int CFCLEAR = 24;
  public static final int PRED = 13;
  public static final int COMMENT = 44;
  public static final int NOBBAG = 33;
  public static final int CLCLEAR = 26;
  public static final int LPAREN = 3;
  public static final int FACINGW = 37;
  public static final int TURNLEFT = 22;
  public static final int FACINGS = 35;
  public static final int EXITINST = 18;
  public static final int CRCLEAR = 28;
  public static final int RPAREN = 4;
  public static final int NOT = 17;
  public static final int AND = 15;
  public static final int FACINGN = 34;
  public static final int OR = 16;
  public static final int SEMICOL = 2;
  public static final int CLASS = 7;
  public static final int FACINGE = 36;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int RKEY = 6;
  public static final int error = 1;
  public static final int ANYBBAG = 32;
  public static final int NUMBER = 45;
  public static final int VOID = 8;
  public static final int CFBLOCK = 25;
  public static final int NAME = 43;
  public static final int NOFACINGW = 41;
  public static final int NONEXTB = 31;
  public static final int ITERATE = 11;
  public static final int SUCC = 14;
  public static final int MOVE = 19;
  public static final int NEXTB = 30;
  public static final int NOFACINGS = 39;
  public static final int CLBLOCK = 27;
  public static final int ELSE = 9;
  public static final int PICKBPR = 20;
  public static final int NOFACINGN = 38;
  public static final int WHILE = 12;
  public static final int CRBLOCK = 29;
  public static final int NOFACINGE = 40;
  public static final int IFZERO = 42;
  public static final int PUTBPR = 21;
  public static final int TURNOFF = 23;
}

