
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 05 18:00:04 UTC 2014
//----------------------------------------------------

package Compilers.Java;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int LKEY = 5;
  public static final int CFCLEAR = 25;
  public static final int PRED = 14;
  public static final int COMMENT = 45;
  public static final int NOBBAG = 34;
  public static final int CLCLEAR = 27;
  public static final int LPAREN = 3;
  public static final int FACINGW = 38;
  public static final int TURNLEFT = 23;
  public static final int FACINGS = 36;
  public static final int EXITINST = 19;
  public static final int CRCLEAR = 29;
  public static final int RPAREN = 4;
  public static final int DEFINE = 9;
  public static final int NOT = 18;
  public static final int AND = 16;
  public static final int FACINGN = 35;
  public static final int OR = 17;
  public static final int SEMICOL = 2;
  public static final int CLASS = 7;
  public static final int FACINGE = 37;
  public static final int IF = 11;
  public static final int EOF = 0;
  public static final int RKEY = 6;
  public static final int error = 1;
  public static final int ANYBBAG = 33;
  public static final int NUMBER = 46;
  public static final int VOID = 8;
  public static final int CFBLOCK = 26;
  public static final int NAME = 44;
  public static final int NOFACINGW = 42;
  public static final int NONEXTB = 32;
  public static final int ITERATE = 12;
  public static final int SUCC = 15;
  public static final int MOVE = 20;
  public static final int NEXTB = 31;
  public static final int NOFACINGS = 40;
  public static final int CLBLOCK = 28;
  public static final int ELSE = 10;
  public static final int PICKBPR = 21;
  public static final int NOFACINGN = 39;
  public static final int WHILE = 13;
  public static final int CRBLOCK = 30;
  public static final int NOFACINGE = 41;
  public static final int IFZERO = 43;
  public static final int PUTBPR = 22;
  public static final int TURNOFF = 24;
}

