
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 02 01:08:45 CST 2014
//----------------------------------------------------

package CompilerPascalES;

/** CUP generated class containing symbol constants. */
public class SymbolsPascal {
  /* terminals */
  public static final int CFCLEAR = 31;
  public static final int PRED = 20;
  public static final int NOBBAG = 40;
  public static final int BEGPROG = 8;
  public static final int CLCLEAR = 33;
  public static final int LPAREN = 3;
  public static final int FACINGW = 44;
  public static final int TURNLEFT = 29;
  public static final int FACINGS = 42;
  public static final int BEGEXEC = 6;
  public static final int CRCLEAR = 35;
  public static final int EXITINST = 25;
  public static final int RPAREN = 4;
  public static final int NOT = 24;
  public static final int AND = 22;
  public static final int FACINGN = 41;
  public static final int OR = 23;
  public static final int SEMICOL = 2;
  public static final int BEGIN = 7;
  public static final int FACINGE = 43;
  public static final int IF = 15;
  public static final int EOF = 0;
  public static final int ANYBBAG = 39;
  public static final int error = 1;
  public static final int NUMBER = 51;
  public static final int DEFINST = 9;
  public static final int CFBLOCK = 32;
  public static final int ENDPROG = 14;
  public static final int NAME = 50;
  public static final int NOFACINGW = 48;
  public static final int NONEXTB = 38;
  public static final int ITERATE = 16;
  public static final int SUCC = 21;
  public static final int MOVE = 26;
  public static final int TIMES = 18;
  public static final int NEXTB = 37;
  public static final int NOFACINGS = 46;
  public static final int CLBLOCK = 34;
  public static final int ELSE = 11;
  public static final int ENDEXEC = 13;
  public static final int PICKBPR = 27;
  public static final int NOFACINGN = 45;
  public static final int WHILE = 19;
  public static final int CRBLOCK = 36;
  public static final int THEN = 17;
  public static final int NOFACINGE = 47;
  public static final int END = 12;
  public static final int IFZERO = 49;
  public static final int PUTBPR = 28;
  public static final int AS = 5;
  public static final int TURNOFF = 30;
  public static final int DO = 10;
}

